### ISSUE TITLE
New Clock Display Customizations

### ISSUE THREAD

**Issue by pogo555** [thehale/BinaryClock#11]
Great app. Simple and intuitive.

Setting the dot colours to be all the same is fiddly. Could you add a lock button?

The display is just too big. Could you allow it to be resized?

A home screen widget would be excellent.

**Comment by thehale** [comment]
Hello @pogo555 ! Thanks for the feedback!

> Setting the dot colours to be all the same is fiddly. Could you add a lock button?

I'm not sure what you mean by this comment. Are you asking for the ability to change the color of individual dots so that you can have a multi-colored clock? Or something else?

Currently, the dots are only available in green, though issues #3 and #8 track feature requests to further customize all the dots.

> The display is just too big. Could you allow it to be resized?

What else would you like to see on the screen besides the clock? Or are you asking for the in-app clock to be full-screen but with smaller dots? Or something else?

> A home screen widget would be excellent.

I agree. Unfortunately, because this app is written in React Native, and widgets on Android/iOS can't easily be created with JS views, this feature won't be implemented any time soon. See issue #12 for more details.

**Comment by thehale** [comment]
@pogo555 since I haven't heard back yet, I'm going to close this issue. Feel free to respond though, at which point I'll reopen the issue for further discussion.
